
version: 2
jobs:
    build:
        docker:
            - image: siorellana/siorellana-webpage
        working_directory: ~/repo
        steps:
            - checkout
            - run:
                name: Compilando el codigo
                command: hugo
            - run:
                name: Firebase Deploy
                command: firebase deploy --token "$FIREBASE_DEPLOY_TOKEN" --only hosting